---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: leader-election

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election

spec:
  replicas: 3
  selector:
    matchLabels:
      app: leader-election

  template:
    metadata:
      labels:
        app: leader-election

    spec:
      serviceAccountName: leader-election
      containers:
        - name: leader-election
          image: leader-election
          imagePullPolicy: Never
